name: CI

on:
  push:
    branches: [main, "release/**"]
  pull_request:

permissions:
  contents: read

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - run: bash -n setup.sh backend-setup.sh coder-setup.sh gitlab-setup.sh certify.sh
      - run: shellcheck setup.sh backend-setup.sh coder-setup.sh gitlab-setup.sh certify.sh
